# Generated by Django 5.0.4 on 2025-01-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cjapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('counselling_booking', 'Counselling Booking Request'), ('livesession_request', 'Live Session Request'), ('question_creation', 'Question Creation'), ('task_created', 'Task Created'), ('task_updated', 'Task Updated'), ('review_required', 'Review Required'), ('review_completed', 'Review Completed'), ('deletion_request', 'Deletion Request'), ('deletion_approved', 'Deletion Approved'), ('deletion_rejected', 'Deletion Rejected')], max_length=50),
        ),
    ]
