# Generated by Django 5.0.4 on 2025-01-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cjapp', '0002_alter_notification_notification_type'),
        ('question_bank', '0042_category_deleted_at_category_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='question',
        ),
        migrations.AddField(
            model_name='task',
            name='number_of_questions',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='question_type',
            field=models.CharField(blank=True, choices=[('mcq_text', 'Multiple Choice - Text-based'), ('mcq_image', 'Multiple Choice - Image-based'), ('mcq_mixed', 'Multiple Choice - Text-image mixed'), ('mcq_audio', 'Multiple Choice - Audio-based'), ('mcq_video', 'Multiple Choice - Video-based'), ('mcq_paragraph', 'Multiple Choice - Paragraph-based'), ('cus_hotspot_single', 'Multiple Choice - Hotspot Single Answer'), ('cus_hotspot_multiple', 'Multiple Choice - Hotspot Multiple Answers'), ('mcq_flash', 'Multiple Choice - Flash-based'), ('fib_text', 'Fill in the Blank - Text-based'), ('fib_image', 'Fill in the Blank - Image-based'), ('fib_audio', 'Fill in the Blank - Audio-based'), ('fib_video', 'Fill in the Blank - Video-based'), ('fib_paragraph', 'Fill in the Blank - Paragraph-based'), ('fib_flash', 'Fill in the Blank - Flash-based'), ('cus_grid', 'Grid List Selection Items'), ('cus_match', 'Match The Following'), ('psy_ranking', 'Psychometric Simple Ranking Scale'), ('psy_rank_n_rate', 'Psychometric First Rank-Then Rate Scale'), ('psy_rating', 'Psychometric Standard Rating Scale'), ('psy_forced_single', 'Psychometric Forced-Choice Scale – Single Level Rating'), ('psy_forced_two', 'Psychometric Forced-Choice Scale – Two-Level Rating')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='questions',
            field=models.ManyToManyField(blank=True, default=None, related_name='tasks', to='question_bank.question'),
        ),
        migrations.AddField(
            model_name='task',
            name='questions_created',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
