# Generated by Django 5.0.4 on 2025-01-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cjapp', '0003_remove_task_question_task_number_of_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('counselling_booking', 'Counselling Booking Request'), ('livesession_request', 'Live Session Request'), ('question_creation', 'Question Creation'), ('content_review', 'Content Review'), ('psychometric_review', 'Psychometric Review'), ('final_approval', 'Final Approval'), ('deletion_request', 'Deletion Request'), ('deletion_approved', 'Deletion Approved'), ('deletion_rejected', 'Deletion Rejected')], max_length=50),
        ),
    ]
