# Generated by Django 5.0.4 on 2024-08-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='flash_items_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
