# Generated by Django 5.0.4 on 2024-08-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0003_alter_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='case_sensitive',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='objective',
            field=models.TextField(blank=True, null=True, verbose_name='Question Objective'),
        ),
        migrations.AlterField(
            model_name='question',
            name='cognitive_level',
            field=models.CharField(choices=[('knowledge', 'Knowledge'), ('comprehension', 'Comprehension'), ('application', 'Application'), ('analysis', 'Analysis'), ('synthesis', 'Synthesis'), ('evaluation', 'Evaluation')], default='knowledge', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty_level',
            field=models.IntegerField(blank=True, choices=[('veasy', 'Very Easy'), ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('vhard', 'Very Hard')], null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('approved', 'Approved'), ('inactive', 'Inactive')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
