# Generated by Django 5.0.4 on 2024-08-20 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0004_question_case_sensitive_question_instructions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='objective',
            new_name='objectives',
        ),
    ]
