# Generated by Django 5.0.4 on 2024-08-20 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0007_question_negative_score_alter_question_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotspotItem',
        ),
    ]
