# Generated by Django 5.0.4 on 2024-08-20 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0008_delete_hotspotitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='question_bank.category'),
        ),
        migrations.AlterField(
            model_name='question',
            name='cognitive_level',
            field=models.CharField(blank=True, choices=[('knowledge', 'Knowledge'), ('comprehension', 'Comprehension'), ('application', 'Application'), ('analysis', 'Analysis'), ('synthesis', 'Synthesis'), ('evaluation', 'Evaluation')], default='knowledge', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(blank=True, choices=[('mcq_text', 'Multiple Choice - Text-based'), ('mcq_image', 'Multiple Choice - Image-based'), ('mcq_mixed', 'Multiple Choice - Text-image mixed'), ('mcq_audio', 'Multiple Choice - Audio-based'), ('mcq_video', 'Multiple Choice - Video-based'), ('mcq_paragraph', 'Multiple Choice - Paragraph-based'), ('mcq_hotspot_single', 'Multiple Choice - Hotspot Single Answer'), ('mcq_hotspot_multiple', 'Multiple Choice - Hotspot Multiple Answers'), ('mcq_flash', 'Multiple Choice - Flash-based'), ('fib_text', 'Fill in the Blank - Text-based'), ('fib_image', 'Fill in the Blank - Image-based'), ('fib_audio', 'Fill in the Blank - Audio-based'), ('fib_video', 'Fill in the Blank - Video-based'), ('fib_paragraph', 'Fill in the Blank - Paragraph-based'), ('fib_flash', 'Fill in the Blank - Flash-based'), ('fib_match', 'Fill in the Blank - Match The Following'), ('psy_simple', 'Psychometric Simple Ranking Scale'), ('psy_first', 'Psychometric First Rank-Then Rate Scale'), ('psy_standard', 'Psychometric Standard Rating Scale'), ('psy_forced_single', 'Psychometric Forced-Choice Scale – Single Level Rating'), ('psy_forced_two', 'Psychometric Forced-Choice Scale – Two-Level Rating')], max_length=20, null=True),
        ),
    ]
