# Generated by Django 5.0.4 on 2024-08-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0009_alter_question_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('veasy', 'Very Easy'), ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('vhard', 'Very Hard')], max_length=20, null=True),
        ),
    ]
