# Generated by Django 5.0.4 on 2024-08-21 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0010_alter_question_difficulty_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='flash_interval',
            new_name='timer_interval',
        ),
    ]
