# Generated by Django 5.0.4 on 2024-08-21 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0013_question_is_multiple_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='grid_cols',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='grid_rows',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GridOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(blank=True, null=True)),
                ('col', models.IntegerField(blank=True, null=True)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='question_grid/')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grid_options', to='question_bank.question')),
            ],
        ),
    ]
