# Generated by Django 5.0.4 on 2024-08-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0015_alter_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='grid_type',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(blank=True, choices=[('mcq_text', 'Multiple Choice - Text-based'), ('mcq_image', 'Multiple Choice - Image-based'), ('mcq_mixed', 'Multiple Choice - Text-image mixed'), ('mcq_audio', 'Multiple Choice - Audio-based'), ('mcq_video', 'Multiple Choice - Video-based'), ('mcq_paragraph', 'Multiple Choice - Paragraph-based'), ('mcq_hotspot_single', 'Multiple Choice - Hotspot Single Answer'), ('mcq_hotspot_multiple', 'Multiple Choice - Hotspot Multiple Answers'), ('mcq_flash', 'Multiple Choice - Flash-based'), ('fib_text', 'Fill in the Blank - Text-based'), ('fib_image', 'Fill in the Blank - Image-based'), ('fib_audio', 'Fill in the Blank - Audio-based'), ('fib_video', 'Fill in the Blank - Video-based'), ('fib_paragraph', 'Fill in the Blank - Paragraph-based'), ('fib_flash', 'Fill in the Blank - Flash-based'), ('cus_grid', 'Grid List Selection Items'), ('cus_match', 'Match The Following'), ('psy_simple', 'Psychometric Simple Ranking Scale'), ('psy_first', 'Psychometric First Rank-Then Rate Scale'), ('psy_standard', 'Psychometric Standard Rating Scale'), ('psy_forced_single', 'Psychometric Forced-Choice Scale – Single Level Rating'), ('psy_forced_two', 'Psychometric Forced-Choice Scale – Two-Level Rating')], max_length=20, null=True),
        ),
    ]
