# Generated by Django 5.0.4 on 2024-08-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0017_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_multiple_answer',
            field=models.BooleanField(default=False),
        ),
    ]
