# Generated by Django 5.0.4 on 2024-09-09 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0019_alter_question_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashitem',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_options', to='question_bank.question'),
        ),
        migrations.AlterField(
            model_name='matchitem',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_options', to='question_bank.question'),
        ),
    ]
