# Generated by Django 5.0.4 on 2024-09-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0020_alter_flashitem_question_alter_matchitem_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionitem',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_score',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='question',
            name='incorrect_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
