# Generated by Django 5.0.4 on 2024-09-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0025_alter_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingitem',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='items',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='question',
            name='scale_end',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='question',
            name='scale_start',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='RankingItem',
        ),
        migrations.DeleteModel(
            name='RatingItem',
        ),
    ]
