# Generated by Django 5.0.4 on 2024-10-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0026_remove_ratingitem_question_question_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ranking_structure',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
