# Generated by Django 5.0.4 on 2024-10-09 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0027_question_ranking_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PsyRankGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PsyStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='question_bank.psycategory')),
            ],
        ),
        migrations.CreateModel(
            name='PsyRankGroupStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='question_bank.psyrankgroup')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_groups', to='question_bank.psystatement')),
            ],
        ),
        migrations.CreateModel(
            name='PsySubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='question_bank.psycategory')),
            ],
        ),
        migrations.AddField(
            model_name='psystatement',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='question_bank.psysubcategory'),
        ),
    ]
