# Generated by Django 5.0.4 on 2024-10-23 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0028_psycategory_psyrankgroup_psystatement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsyRatingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('value', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_options', to='question_bank.question')),
            ],
        ),
    ]
