# Generated by Django 5.0.4 on 2024-10-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0029_psyratingitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='timer_interval',
            field=models.PositiveIntegerField(blank=True, default=60, help_text='Interval in seconds', null=True),
        ),
    ]
