# Generated by Django 5.0.4 on 2024-10-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0030_alter_question_timer_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='timer_interval',
            field=models.PositiveIntegerField(blank=True, help_text='Interval in seconds', null=True),
        ),
    ]
