# Generated by Django 5.0.4 on 2024-10-31 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0032_question_paragraph_interval_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='timer_interval',
            new_name='flash_interval',
        ),
    ]
