# Generated by Django 5.0.4 on 2024-11-06 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0033_rename_timer_interval_question_flash_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchitem',
            name='score',
        ),
    ]
