# Generated by Django 5.0.4 on 2024-11-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0034_remove_matchitem_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='flash_interval',
            field=models.PositiveIntegerField(blank=True, default=5, help_text='Interval in seconds', null=True),
        ),
    ]
