# Generated by Django 5.0.4 on 2024-11-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0035_alter_question_flash_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='paragraph_interval',
            field=models.PositiveIntegerField(blank=True, default=10, help_text='Interval in seconds', null=True),
        ),
    ]
