# Generated by Django 5.0.4 on 2025-01-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0036_alter_question_paragraph_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('active', 'Active'), ('inactive', 'Inactive')], default='draft', max_length=20),
        ),
    ]
