# Generated by Django 5.0.4 on 2025-01-10 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0038_deletionrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deletionrequest',
            name='subcategory',
        ),
    ]
