# Generated by Django 5.0.4 on 2025-01-10 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0039_remove_deletionrequest_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletionrequest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='question_bank.category'),
        ),
        migrations.AlterField(
            model_name='deletionrequest',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='question_bank.question'),
        ),
    ]
