# Generated by Django 5.0.4 on 2025-01-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0042_category_deleted_at_category_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_score',
        ),
        migrations.RemoveField(
            model_name='question',
            name='incorrect_score',
        ),
        migrations.AddField(
            model_name='question',
            name='right_score',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='wrong_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
