# Generated by Django 5.0.4 on 2025-01-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0043_remove_question_correct_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='grid_cols',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='grid_rows',
            field=models.IntegerField(default=1),
        ),
    ]
