# Generated by Django 5.0.4 on 2025-01-31 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0044_alter_question_grid_cols_alter_question_grid_rows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='items',
        ),
        migrations.RemoveField(
            model_name='question',
            name='scale_end',
        ),
        migrations.RemoveField(
            model_name='question',
            name='scale_start',
        ),
    ]
