# Generated by Django 5.0.4 on 2025-03-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0046_alter_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='forced_choice_subtype',
            field=models.CharField(choices=[('standard', 'Standard (No Contrast Variables)'), ('with_contrast_variable', 'With Contrast Variables (CV1 & CV2)')], default='standard', help_text='Only applies to Forced-Choice Single Level questions', max_length=30),
        ),
    ]
