# Generated by Django 5.0.4 on 2024-09-05 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='variable',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='variable',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='assessment.assessment'),
        ),
    ]
