# Generated by Django 5.0.4 on 2024-09-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_assessment_variable_alter_variable_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='description_img',
            field=models.ImageField(blank=True, null=True, upload_to='assessment_images/'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='instructions_img',
            field=models.ImageField(blank=True, null=True, upload_to='assessment_images/'),
        ),
        migrations.DeleteModel(
            name='Variable',
        ),
    ]
