# Generated by Django 5.0.4 on 2024-09-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_assessment_description_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='variable',
            new_name='structure',
        ),
        migrations.AddField(
            model_name='assessment',
            name='assigned_count',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='assessment',
            name='delivery_count',
            field=models.JSONField(default=dict),
        ),
    ]
