# Generated by Django 5.0.4 on 2024-09-11 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_rename_variable_assessment_structure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='assigned_count',
            new_name='level_counts',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='delivery_count',
        ),
    ]
