# Generated by Django 5.0.4 on 2024-09-12 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_remove_assessment_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='level_counts',
        ),
    ]
