# Generated by Django 5.0.4 on 2024-09-12 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_remove_assessment_level_counts'),
        ('question_bank', '0022_flashitem_score_gridoption_score_matchitem_score'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssessmentQuestion',
            new_name='Question',
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='assessment.assessment')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='assessment.section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.section'),
        ),
        migrations.DeleteModel(
            name='AssessmentSection',
        ),
    ]
