# Generated by Django 5.0.4 on 2024-09-12 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0009_rename_assessmentquestion_question_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionassignment',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.question'),
        ),
        migrations.AlterField(
            model_name='score',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.question'),
        ),
    ]
