# Generated by Django 5.0.4 on 2024-09-12 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0010_alter_questionassignment_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionassignment',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='questionassignment',
            name='question',
        ),
        migrations.RemoveField(
            model_name='score',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='score',
            name='question',
        ),
        migrations.DeleteModel(
            name='DisplayParameters',
        ),
        migrations.DeleteModel(
            name='QuestionAssignment',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
