# Generated by Django 5.0.4 on 2024-09-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0011_remove_questionassignment_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='level_counts',
            field=models.JSONField(default=dict),
        ),
    ]
