# Generated by Django 5.0.4 on 2024-09-12 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0013_alter_question_order'),
        ('question_bank', '0022_flashitem_score_gridoption_score_matchitem_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='is_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='section',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='question_bank.question'),
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
