# Generated by Django 5.0.4 on 2024-09-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0014_section_is_section_section_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='right_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='wrong_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
