# Generated by Django 5.0.4 on 2024-09-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0015_section_right_score_section_wrong_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='right_score',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
