# Generated by Django 5.0.4 on 2024-09-17 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0016_alter_section_right_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='right_score',
        ),
        migrations.RemoveField(
            model_name='section',
            name='wrong_score',
        ),
    ]
