# Generated by Django 5.0.4 on 2024-09-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0017_remove_section_right_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='right_score',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='section',
            name='wrong_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
