# Generated by Django 5.0.4 on 2024-10-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0020_assessmentsession_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='duration_minutes',
            field=models.IntegerField(default=60),
        ),
    ]
