# Generated by Django 5.0.4 on 2024-11-02 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0022_assessment_display_order'),
        ('question_bank', '0033_rename_timer_interval_question_flash_interval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmentsession',
            old_name='student',
            new_name='user',
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='current_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='question_bank.question'),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('suspended', 'Suspended'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='time_remaining',
            field=models.IntegerField(help_text='Remaining time in seconds', null=True),
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_data', models.JSONField()),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('response_time', models.DateTimeField(auto_now=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_bank.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessmentsession')),
            ],
            options={
                'unique_together': {('session', 'question')},
            },
        ),
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
    ]
