# Generated by Django 5.0.4 on 2025-01-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0024_remove_assessment_level_counts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsession',
            name='scores',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
