# Generated by Django 5.0.4 on 2025-01-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0025_assessmentsession_scores_questionresponse_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='status',
            field=models.CharField(choices=[('answered', 'Answered'), ('skipped', 'Skipped')], default='skipped', max_length=10),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='answer_data',
            field=models.JSONField(default=dict),
        ),
    ]
