# Generated by Django 5.0.4 on 2025-02-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0026_questionresponse_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal Assessment'), ('psychometric', 'Psychometric Assessment')], default='normal', max_length=20),
        ),
    ]
