# Generated by Django 5.0.4 on 2025-02-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0027_assessment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='psy_score',
            field=models.JSONField(default=dict),
        ),
    ]
