# Generated by Django 5.0.4 on 2024-07-22 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=500, null=True)),
            ],
            options={
                'permissions': (('counselling_category_add', 'Can add Counselling category'), ('counselling_category_change', 'Can change Counselling category'), ('counselling_category_view', 'Can view Counselling category'), ('counselling_category_delete', 'Can delete Counselling category')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('timeslots', models.CharField(help_text='timeslots are in 24 hours format', max_length=100, verbose_name='Timeslots')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated on')),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': ('update_counselling',),
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Booking Date')),
                ('timeslot', models.TextField(choices=[('1', '9-10 (Morning)'), ('2', '10-11 (Morning)'), ('3', '11-12 (Morning)'), ('4', '12-13 (Afternoon)'), ('5', '13-14 (Afternoon)'), ('6', '14-15 (Afternoon)'), ('7', '15-16 (Evening)'), ('8', '16-17 (Evening)'), ('9', '17-18 (Evening)'), ('10', '18-19 (Evening)')], null=True, verbose_name='Timeslot')),
                ('topic', models.CharField(help_text='Describe the topic or issue', max_length=500, verbose_name='Topic/Issue')),
                ('booked', models.DateTimeField(null=True, verbose_name='Booked on')),
                ('paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('rzp_payment_id', models.TextField(blank=True, null=True)),
                ('rzp_order_id', models.TextField(blank=True, null=True)),
                ('rzp_signature', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Booked'), (1, 'Completed'), (2, 'Cancelled')], default=0, null=True, verbose_name='Status')),
                ('reason', models.TextField(blank=True, help_text='Reason for Cancellation', max_length=500, null=True)),
                ('counselee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselee', to=settings.AUTH_USER_MODEL)),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counsellor', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselling.category')),
            ],
            options={
                'default_permissions': ('view_counselling', 'add_counselling', 'cancel_counselling'),
            },
        ),
    ]
