# Generated by Django 5.0.4 on 2025-03-24 08:55

import django.db.models.deletion
import django_quill.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0028_questionresponse_psy_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('report_count', models.PositiveIntegerField(default=1)),
                ('paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('rzp_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('rzp_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('rzp_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('objectives', django_quill.fields.QuillField(blank=True, null=True)),
                ('description', django_quill.fields.QuillField(blank=True, null=True)),
                ('description_img', models.ImageField(blank=True, null=True, upload_to='report_images/')),
                ('report_type', models.CharField(choices=[('descriptive', 'Descriptive'), ('interpretative', 'Interpretative'), ('group', 'Group'), ('typological', 'Typological'), ('question_level', 'Question Level')], max_length=20)),
                ('score_level', models.JSONField(default=list, help_text='Selected score levels')),
                ('score_conversion', models.CharField(choices=[('percentage', 'Percentage'), ('percentile', 'Percentile'), ('sten', 'STEN'), ('stenine', 'STENINE'), ('raw', 'Raw Score')], default='percentage', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_code_count', models.PositiveIntegerField(default=4, help_text='Number of contrast variables to include in type code')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_configurations', to='assessment.assessment')),
                ('candidates', models.ManyToManyField(blank=True, related_name='report_configurations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContrastVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(blank=True, help_text='Reference to question subcategory', max_length=255, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('color', models.CharField(default='#007bff', max_length=20)),
                ('description', django_quill.fields.QuillField(blank=True, null=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrast_variables', to='reports.reportconfiguration')),
            ],
            options={
                'unique_together': {('configuration', 'subcategory')},
            },
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_range', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_range', models.DecimalField(decimal_places=2, max_digits=5)),
                ('color', models.CharField(default='#007bff', max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('description', django_quill.fields.QuillField(blank=True, null=True)),
                ('assessment_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.section')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='reports.reportconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='TypeBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_range', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_range', models.DecimalField(decimal_places=2, max_digits=5)),
                ('color', models.CharField(default='#007bff', max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('description', django_quill.fields.QuillField(blank=True, null=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_bands', to='reports.reportconfiguration')),
                ('contrast_variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='reports.contrastvariable')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='generated_reports/%Y/%m/%d/')),
                ('assessment_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessmentsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reportconfiguration')),
            ],
            options={
                'unique_together': {('configuration', 'assessment_session')},
            },
        ),
        migrations.CreateModel(
            name='Cutoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cutoff_label', models.CharField(max_length=100)),
                ('above_cutoff_description', django_quill.fields.QuillField(blank=True, null=True)),
                ('below_cutoff_description', django_quill.fields.QuillField(blank=True, null=True)),
                ('assessment_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.section')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutoffs', to='reports.reportconfiguration')),
            ],
            options={
                'unique_together': {('configuration', 'assessment_section')},
            },
        ),
    ]
